version: '2'
services:
  redis-master:
    image: redis:latest
    ports:
    - 6379:6379
    environment:
    - REDIS_REPLICATION_MODE=master
    - ALLOW_EMPTY_PASSWORD=yes
  redis-replica:
    image: redis:latest
    ports:
    - 6380-6382:6379
    depends_on:
    - redis-master
    environment:
    - REDIS_REPLICATION_MODE=slave
    - REDIS_MASTER_HOST=redis-master
    - REDIS_MASTER_PORT_NUMBER=6379
    - ALLOW_EMPTY_PASSWORD=yes
    deploy:
      replicas: 1